service: tfranksystem-api

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    SECRET: ${file(config.${self:provider.stage}.yml):SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "*"

functions:
  authenticate:
    handler: api/auth.authenticate
    events:
      - http:
          path: oauth/token
          method: post
          cors: true
  authorize:
    handler: api/auth.authorize
  get-all-players:
    handler: api/players.getall
    events:
      - http:
          path: players/
          method: get
          cors: true
  get-player:
    handler: api/players.getone
    events:
      - http:
          path: players/{id}
          method: get
          cors: true
  create-player:
    handler: api/players.create
    events:
      - http:
          path: players/
          method: post
          cors: true
          authorizer: authorize
          request:
            template:
              application/json: ${file(apiRequestTemplate.json)}
  get-historical-ranks:
    handler: api/historicalrank.get
    events:
      - http:
          path: players/{id}/historical
          method: get 
          cors: true
  create-match:
    handler: api/matches.create
    events:
      - http:
          path: matches
          method: post
          cors: true
          authorizer: authorize
          request:
            template:
              application/json: ${file(apiRequestTemplate.json)}
  get-matches:
    handler: api/matches.getall
    events:
      - http:
          path: matches
          method: get
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
  serverless-offline:
    noTimeout

resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
